/* Autogenerated, do not edit */
#ifndef COMPEL_SO_VERSION_H__
#define COMPEL_SO_VERSION_H__
#define COMPEL_SO_VERSION ""
#define COMPEL_SO_VERSION_MAJOR  1
#define COMPEL_SO_VERSION_MINOR  0
#define COMPEL_SO_VERSION_SUBLEVEL  0
#endif /* COMPEL_SO_VERSION_H__ */
