// +build autogen

// Package dockerversion is auto-generated at build-time
package dockerversion

// Default build-time variable for library-import.
// This file is overridden on build with build-time informations.
const (
	GitCommit string = "84aa0ef-unsupported"
	Version   string = "1.10.0-dev"
	BuildTime string = "2017-01-14T18:57:59.701393169-05:00"

	IAmStatic string = "true"
	InitSHA1  string = ""
	InitPath  string = ""
)
// AUTOGENERATED FILE; see /home/peter/peter_used/Docker-cr-combined/hack/make/.go-autogen
